[tools]
arduino = "1.5"
uv = "0.12"
"pipx:ok-serial" = "0.8"
"pipx:ok-serial-terminal" = "0.4"

[env]
ARDUINO_DIRECTORIES_DATA = "{{config_root}}/arduino.tmp"
ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL = "true"

[hooks]
postinstall = """
  echo '[git]'; git lfs install --local && git lfs pull
  echo '[arduino]'; arduino-cli update
"""

[settings]
experimental = true
